USE shop;
ALTER TABLE users ENCRYPTED=YES ENCRYPTION_KEY_ID=2;
ALTER TABLE addresses ENCRYPTED=YES ENCRYPTION_KEY_ID=2;
ALTER TABLE payment_methods ENCRYPTED=YES ENCRYPTION_KEY_ID=2;
ALTER TABLE products ENCRYPTED=YES ENCRYPTION_KEY_ID=1;
ALTER TABLE orders ENCRYPTED=YES ENCRYPTION_KEY_ID=1;
ALTER TABLE order_items ENCRYPTED=YES ENCRYPTION_KEY_ID=1;
